plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: "pub global run cider version ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - master
