plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "semantic-release-pub"
    - publsihPub: false
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - master
