plugins:
  - - "@semantic-release/commit-analyzer"
    - presets: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - presets: conventionalcommits
  - "@semantic-release/github"
  - - "semantic-release-pub"
    - publishPub: false
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - master
