include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 120

analyzer:
  exclude:
    - lib/src/models/*.mapper.dart

linter:
  rules:
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
