include: package:very_good_analysis/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     public_member_api_docs: false

analyzer:
  exclude:
    - lib/src/models/*.g.dart

linter:
  rules:
    use_enums: true
    use_super_parameters: true
