name: market_client
description: A starting point for Dart libraries or applications.
version: 1.2.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.4.0
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  test: ^1.20.1
  very_good_analysis: ^2.4.0
