name: market_client
description: A Dart WFM API client wrapper
version: 4.6.3
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  dart_mappable: ^4.5.0
  equatable: ^2.0.7
  http: ^1.3.0
  intl: ">=0.19.0 <1.0.0" # Can conflict with Flutter if pinned
  meta: ">=1.15.0 <2.0.0" # Can conflict with Flutter if pinned
  web_socket_client: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.5.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
