name: market_client
description: A starting point for Dart libraries or applications.
version: 4.1.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ">=2.0.5 <3.0.0"
  http: ">=1.0.0 <2.0.0"
  json_annotation: ">=4.8.1 <5.0.0"
  meta: ">=1.9.1 <2.0.0"
  uuid: ">=4.1.0 <5.0.0"
  web_socket_client: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.8
  very_good_analysis: ^5.1.0
