name: market_client
description: A Dart WFM API client wrapper
version: 4.4.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ^3.6.0

dependencies:
  dart_mappable: ^4.3.0
  equatable: ^2.0.7
  http: ^1.3.0
  intl: ">=0.19.0 <1.0.0"
  meta: ">=1.15.0 <2.0.0"
  web_socket_client: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.3.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
