name: market_client
description: A starting point for Dart libraries or applications.
version: 3.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
