name: market_client
description: A starting point for Dart libraries or applications.
version: 2.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  fresh: ^0.4.1
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^2.4.0
