name: Dart Docs
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1.3
        with:
          release-channel: stable

      - name: Install dependacies
        run: |
          dart pub get
          dart pub global activate dartdoc
      - name: Generate docs
        run: dartdoc

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api
