name: Dart Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1.6.1
      - name: Install dependacies
        run: |
          dart pub get
          dart pub global activate dartdoc
      - name: Generate docs
        run: dartdoc
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api
